### ISSUE TITLE
Determine how to handle long names in results graph

### ISSUE THREAD

**Issue by ArendPeter** [Equal-Vote/star-server#290] opened 2023-06-13 07:34 UTC
Looks great! For the long name case I'm wondering if it'd be better to just truncate names past a certain length. Probably good as is for now.

_Originally posted by @mikefranze in https://github.com/Equal-Vote/star-server/issues/286#issuecomment-1588476240_

**Comment by mikefranze** [comment] 2023-11-22 05:23
Duplicate of #328

**Closed by mikefranze** 2023-11-22 05:23 UTC
